### ISSUE TITLE
awk executable wrong format

### ISSUE THREAD

**Issue by Manu343726** [GathSystems/CygwinPortable#15]
Hi.

I have just installed the Portable Apps version from [here](http://www.cybesystems.com/index.php?option=com_jdownloads&view=downloads&Itemid=196) as you described in the readme. 

That fresh install fails to execute awk since `/usr/bin/awk` is an ASCII text file. I'm sure this can be easily reproduced by doing a fresh install and executing `file $(which awk)` on bash. This prevents for using `apt-cyg` for example. 

I have fixed it by reinstalling awk through cygwin setup manager.

**Comment by FlipB** [comment]
Just FYI, they seem to have the same issue on the chocolatey packages.
See https://github.com/chocolatey/chocolatey-coreteampackages/issues/101 for details.

**Comment by QiangF** [comment]
You have to do all operations in windows. If the files are copied from linux, something can be wrong.

**Comment by LORDofDOOM** [comment]
Should be fixed in latest version
