### ISSUE TITLE
Can't run X applications?

### ISSUE THREAD

**Issue by QiangF** [GathSystems/CygwinPortable#20]
Hi everyone,
I installed xorg-server and xinit with apt-cyg. Then use the following command
to run xterm. 

```
XWin :0 -clipboard -multiwindow
DISPLAY=:0.0 xterm
```

Nothing shows up, "ps -e | grep X" also doesn't show anything.
What is wrong?
Thank you for your help.

**Comment by LORDofDOOM** [comment]
Hi,

yes, use this package to install X11:

https://github.com/GathSystems/CygwinPortable/blob/master/App/DefaultData/Packages/Default%20X11.txt

see line 116 in https://github.com/GathSystems/CygwinPortable/blob/master/Source/Form_Traymenu.cs

**Comment by QiangF** [comment]
But nothing happens after clicking the tray menu start xserver. I install x with this command:

    apt-cyg install xinit xorg-server

Is there anything missing?

**Comment by LORDofDOOM** [comment]
Hi,

I dont try it with apt-cyg - I'll check this

**Comment by LORDofDOOM** [comment]
Fixed in latest build - THX for report
