### ISSUE TITLE
CygwinConfig.exe requires admin priviledge

### ISSUE THREAD

**Issue by JamesHirschorn** [GathSystems/CygwinPortable#21]
When I run it, UAC asks me for the administrator password.

Obviously I should be able to setup Cygwin without this, yes?

**Comment by JamesHirschorn** [comment]
OK, I can use --no-admin.

**Comment by tYYGH** [comment]
Why is this not the default for CygwinPortable?

**Comment by LORDofDOOM** [comment]
I dont add this option as default because I use the program with full access rights. This may break some script... 

I'll add option to set this in config - So you can set this if needed
