### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Gandalf73** [GathSystems/CygwinPortable#23]
Sorry,
I am a newly in Github and I do a wrong task.
I try Cygwin Portable.
I explore the project but I push mouse botton when it is over the "fork" option.
How can I skip this from the "my repository"?.
It is an error because my focus is only follow the project and write comments on this.
Sorry again
Could you help me to skip this?
I thank you again for your precious assistance
Regards
A

**Comment by LORDofDOOM** [comment]
Hi,

simply delete the repository -> Open your fork -> Go to settings -> go to "Danger Zone" -> Delete this repository

**Comment by Gandalf73** [comment]
Hello,
I discovered a little strange behaviour into the Cygwin Portable application. 
I  try to explain it.
When I run "startxwin" from a previous open bash prompt and newly (within it) , some "system tools" from XDG menu, 
(on TrayMenu items),  I see the corresponding items correctly (i.e. I can see a new window with bash prompt of Mintty or UxTerm or XTerm)
On the other hand,
when I start X server with Cygwin menu (throughout X Server Item) and after I run Xterm, Uxterm or Cygwin Terminal (mintty) (always throughout TrayMenu items) ,
I can observe the terminal correct launched on the window but on the top of the prompt it appears "bash: : command not found "
So I think it can be into the batches files script one "spurious or false character" (it seems a space).
Unfortunately I am not able to check into the source.
I hope that my discovery is useful 
Thanks a lot again
Regards
A.
