### ISSUE TITLE
Cannot change user rx permission on Windows8!

### ISSUE THREAD

**Issue by amal-khailtash** [GathSystems/CygwinPortable#24]
For some reason I cannot change user's read/execute permissions on a new install based on "CygwinPortable_1.2.0.0_x64.paf.exe"

```bash
amal@beta ~
$ umask
0022

amal@beta ~
$ umask -S
u=rwx,g=rx,o=rx

amal@beta ~
$ touch test

amal@beta ~
$ ll
total 0
-rwxrw-r--+ 1 amal amal 0 Dec 10 13:59 test*

amal@beta ~
$ chmod a-rwx test

amal@beta ~
$ ll
total 0
-r-x------+ 1 amal amal 0 Dec 10 13:59 test*

amal@beta ~
$ chmod u-rx test

amal@beta ~
$ ll
total 0
-r-x------+ 1 amal amal 0 Dec 10 13:59 test*

amal@beta ~
$ chmod a+rwx test

amal@beta ~
$ ll
total 0
-rwxrwxrwx+ 1 amal amal 0 Dec 10 13:59 test*
```

/etc/fstab is set correctly:

```bash
$ cat /etc/fstab
# /etc/fstab
#
#    This file is read once by the first process in a Cygwin process tree.
#    To pick up changes, restart all Cygwin processes.  For a description
#    see https://cygwin.com/cygwin-ug-net/using.html#mount-table

# This is default anyway:
none /cygdrive cygdrive binary,noacl,posix=0,user 0 0
```

-- Amal

**Comment by LORDofDOOM** [comment]
Hi,

chmod seems correct in your sample - I've try the same and got correct read/execute permission.

The fstab provided in my default installation should be:

```

# /etc/fstab
#
#    This file is read once by the first process in a Cygwin process tree.
#    To pick up changes, restart all Cygwin processes.  For a description
#    see https://cygwin.com/cygwin-ug-net/using.html#mount-table

# This is default anyway:
none /cygdrive cygdrive binary,posix=0,user 0 0
```

It's possible that cygwin changed something... "noacl" should not be in defaults

**Comment by amal-khailtash** [comment]
I added he noacl based on the README.md file on the main page:

> Recommend /etc/fstab
> 
> You should change /etc/fstab from
> 
> none /cygdrive cygdrive binary,posix=0,user 0 0
> 
> to:
> 
> none /cygdrive cygdrive binary,noacl,posix=0,user 0 0
> 
> The noacl flag ignores filesystem ACLs permissions - For portable (in most cases for static installations too) this is the best setting - With this option you dont write "garbage" permissions to e.g. local rsync backups.

Even without that it is the same problem.  Funny thing is that if I install this on a flash drive (FAT) partition, all permissions (user/group/others) on a file are set "-rwxrwxrwx" and they cannot be changed.

```bash
amal@beta ~
$ touch test

amal@beta ~
$ ll
total 0
-rwxrwxrwx 1 amal amal 0 Dec 11 12:39 test*

amal@beta ~
$ chmod a-rwx test
chmod: changing permissions of 'test': Permission denied
```

I don't understand windows permissions.  Something to do with windows?

-- Amal

**Comment by LORDofDOOM** [comment]
IMHO FAT32 dont support permissions - You need to use NTFS. 

It's possible that this is a cygwin issue - Do you try this with a "real" cygwin (installed) environment ?

**Comment by amal-khailtash** [comment]
Yes, FAT32 might work, but I have a local install on my hard-disk where the portable app is installed and permissions on that one are good.  They are both installed on NTFS partition and in different folders in root C:\ directory.

**Comment by LORDofDOOM** [comment]
Do you run cygwin as admin ?

**Comment by amal-khailtash** [comment]
I tried both as admin and just a regular launch.  Maybe it has to do with the folder I am installing on windows.  Maybe folder permissions are messed up on windows side.
