### ISSUE TITLE
Current ini file is from a newer version of setup-x86_64.exe

### ISSUE THREAD

**Issue by jackjackk** [GathSystems/CygwinPortable#25]
When clicking on "Open Cygwin Setup", I get:
![immagine](https://cloud.githubusercontent.com/assets/3717222/22461435/8e5d6850-e7a9-11e6-89d5-4b420801c7f1.png)
![immagine](https://cloud.githubusercontent.com/assets/3717222/22461443/97ca1f96-e7a9-11e6-936a-373084a64cea.png)

**Comment by LORDofDOOM** [comment]
You can ignore this (still works) - You can also download new cygwin setup -> https://www.cygwin.com/setup-x86_64.exe, reename this file to CygwinConfig.exe and replace \App\Runtime\Cygwin\CygwinConfig.exe

I will add a update button in next version
