### ISSUE TITLE
tmux can't create socket: Permission denied

### ISSUE THREAD

**Issue by dukasvili** [GathSystems/CygwinPortable#28]
I get this error when try to start tmux
`tmux can't create socket: Permission denied`

**Comment by tYYGH** [comment]
I launch tmux like this and it works: `tmux -S ~/.tmsock new -ADsCyg`

**Comment by nishantkumar1292** [comment]
I am also getting the same error.
@tYYGH Your solution works well, but how can I resolve running tmux as non-root user.

**Comment by tYYGH** [comment]
Sorry, I don’t understand the question… What is “root” in Cygwin anyway?

**Comment by nishantkumar1292** [comment]
This command  `tmux -S ~/.tmsock new -ADsCyg` works well.
However when dettach the current session and try attaching it again using `tmux a`, I get the same error `tmux can't create socket: Permission denied`. How can I resolve this?

tmux is running fine when running as root user. The above problem only occurs when I run tmux as non-root user.

**Comment by snth** [comment]
@nishantkumar1292 I guess you probably need to run `tmux -S ~/.tmsock new -ADsCyg attach`.

What I did is set the following in my `.bashrc`:

    alias tmux='tmux -S ~/.tmsock new -ADsCyg'

and then I can just run `tmux` and `tmux attach` in Cygwin (or my case MobaXterm) normally.

**Comment by wingy3181** [comment]
FYI, I set `export TMUX_TMPDIR=~/.tmux/tmp` and now it seems to work. 
Originally I set the alias
However, when I tried to run `~/.tmux/plugins/tpm/bin/update_plugins all` to try and update the plugins via CLI, it would again have permission issues because the internal scripts call tmux and not the alias

**Comment by zeroc0d3** [comment]
This steps work for me:
* Add this line on your `~/.bashrc` or `~/.zshrc`
```
export TMUX_TMPDIR=~/.tmux/tmp
```
* Create folder & change to write mode:
```
mkdir -p ~/.tmux/tmp
chmod 777 -R ~/.tmux/tmp
```
* Reload `~/.bashrc` or `~/.zshrc`
```
$SHELL
```
* Re-run the tmux
```
tmux
```

**Comment by MatthewRClarke** [comment]
The above didn't work. I ended up going this route.
Add this line to your `/etc/fstab`:
```
none /tmp usertemp binary,posix=0 0 0
```

This will use your Windows tmp directory as /tmp which is:
```
C:\Users\MatthewRClarke\AppData\Local\Temp
```

**Comment by xemcerk** [comment]
In my case, I used a root group user to `chmod 777` a whole bunch of directories. It turns out that the tmp file of tmux should be only accessible to yourself, so use my own account to `chomd -R 700 /tmp/tmux-<your tmux uid>` did the trick finally.

**Comment by Walkability** [comment]
The TMUX_TMPDIR solution should work, but I ended up just building tmux from the source. Most likely you are using an outdated version of tmux.
